sudo: required
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - docker
after_success:
  - docker build -t petclinic .
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-west-2)
  - docker tag petclinic:latest 556771014529.dkr.ecr.us-west-2.amazonaws.com/petclinic:latest
  - docker push 556771014529.dkr.ecr.us-west-2.amazonaws.com/petclinic
  - aws ecs run-task --cluster default --region us-east-1 --task-definition petclinic:1
